
export const list = [
  {
    id: 1,
    title: "Classic Burger",
    price: 227000 ,
    img: "img/Classic Burger.jpeg",
    amount: 1,
    kind: "Burger",
  },
  {
    id: 2,
    title: "Cheese Burger",
    price: 238000,
    img: "img/Cheese Burger.jpeg",
    amount: 1,
    kind: "Burger",
  },
  {
    id: 3,
    title: "Majara Burger",
    price: 258000,
    img: "img/Majara Burger.jpeg",
    amount: 1,
    kind: "Burger",
  }, 
  {
    id: 4,
    title: "Mushroom Burger",
    price: 253000,
    img: "img/Mushroom Burger.jpeg",
    amount: 1,
    kind: "Burger",
  }, 
  {
    id: 5,
    title: "Crispy Burger",
    price: 297000,
    img: "img/Crispy Burger.jpeg",
    amount: 1,
    kind: "Burger",
  }, 
  {
    id: 6,
    title: "American Four Cheese Burger",
    price: 467000,
    img: "img/American Four Cheese Burger.jpeg",
    amount: 1,
    kind: "Burger",
  }, 
  {
    id: 7,
    title: "Crispy Chicken Burger",
    price: 197000,
    img: "img/Crispy Chicken Burger.jpeg",
    amount: 1,
    kind: "Burger",
  }, 
  {
    id: 8,
    title: "Diet Chicken Grill Burger",
    price: 188000,
    img: "img/Diet Chicken Grill Burger.jpeg",
    amount: 1,
    kind: "Burger",
  },
  {
    id: 9,
    title: "Majara Pizza 24",
    price: 247000,
    img: "img/Majara Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 10,
    title: "Majara Pizza 34",
    price: 398000,
    img: "img/Majara Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 11,
    title: "Special Pizza 24",
    price: 243000,
    img: "img/Special Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 12,
    title: "Special Pizza 34",
    price: 387000,
    img: "img/Special Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 13,
    title: "Mixed Pizza 24",
    price: 239000,
    img: "img/Mixed Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 14,
    title: "Mixed Pizza 34",
    price: 377000,
    img: "img/Mixed Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 15,
    title: "Mushroom Meat Pizza 24",
    price: 247000,
    img: "img/Mushroom Meat Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 16,
    title: "Mushroom Meat Pizza 34",
    price: 398000,
    img: "img/Mushroom Meat Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 17,
    title: "Roast Beef Pizza 24",
    price: 247000,
    img: "img/Roast Beef Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 18,
    title: "Roast Beef Pizza 34",
    price: 398000,
    img: "img/Roast Beef Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 19,
    title: "Peperoni Pizza 24",
    price: 229000,
    img: "img/Peperoni Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 20,
    title: "Peperoni Pizza 34",
    price: 367000,
    img: "img/Peperoni Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 21,
    title: "Alferedo Bacen Pizza 24",
    price: 247000,
    img: "img/Alferedo Bacen Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 22,
    title: "Alferedo Bacen Pizza 34",
    price: 398000,
    img: "img/Alferedo Bacen Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 23,
    title: "Mexican Pizza 24",
    price: 247000,
    img: "img/Mexican Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 24,
    title: "Mexican Pizza 34",
    price: 398000,
    img: "img/Mexican Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 25,
    title: "Kalzon Pizza 24",
    price: 243000,
    img: "img/Kalzon Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 26,
    title: "Kalzon Pizza 34",
    price: 387000,
    img: "img/Kalzon Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 27,
    title: "Vegetables Pizza 24",
    price: 229000,
    img: "img/Vegetables Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 28,
    title: "Vegetables Pizza 34",
    price: 358000,
    img: "img/Vegetables Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 29,
    title: "Vegeterian Pizza",
    price: 243000,
    img: "img/Vegeterian Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 30,
    title: "Vegeterian Pizza",
    price: 387000,
    img: "img/Vegeterian Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 31,
    title: "Vegan Pizza",
    price: 247000,
    img: "img/Vegan Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
  {
    id: 32,
    title: "Vegan Pizza",
    price: 398000,
    img: "img/Vegan Pizza.jpeg",
    amount: 1,
    kind: "Pizza",
  },
 
  
];
